### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by dholth** [conda/conda-content-trust#100]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Add benchmarks to track performance of this repository.

### Why is this needed?

Xref https://github.com/conda/conda/issues/11154

### What should happen?

This repository will have meaningful benchmarks.

**Comment by beeankha** [comment]
Work is in-progress here: https://github.com/conda/conda-content-trust/pull/95
