### ISSUE TITLE
root documents are cached locally forever

### ISSUE THREAD

**Issue by barabo** [conda/conda-content-trust#104]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When `conda-content-trust` is enabled, it attempts to download successive versions of `X.root.json` from the configured `signing_metadata_url_base` (which would be `https://repo.anaconda.cloud/repo` for many users), saving them to `${CONDA_PREFIX}/etc/X.root.json` locally.

These cached files never expire!  So, in the unlikely events that a root document must be rolled back or was published erroneously, the local copy would be retained - potentially later masking a fixing change.

Also, `conda clean -a` does not remove these files, as suggested in documentation (but I can't seem to find the link to that right now).

**Comment by bhuwan-agarwal** [comment]
@jezdez any update on this? This is going to be a blocker for the upcoming changes in the key_mgr.

**Comment by jezdez** [comment]
@bhuwan-agarwal No update, the ticket description didn't say anything about this blocking something, the severity is purely an indicator of the issue quality, doesn't have a direct result in immediate action unless it's requested.

**Comment by chenghlee** [comment]
> This is going to be a blocker for the upcoming changes in the key_mgr.

@bhuwan-agarwal: why would this be a blocker? (There's an argument to be made that we should _never_ roll back a root key deployment, and in any case, there's a workaround in having the users manually remove the cached `*.root.json`.)

**Comment by LtDan33** [comment]
I would assume we would only ever roll forward if there was an issue?

**Comment by bhuwan-agarwal** [comment]
I think the question is whether conda-content-trust caching the root document locally is the intended behavior or not. If it's working as expected where root documents persist locally even after clearing local cache then perhaps this a non-issue and can be closed.
