### ISSUE TITLE
Enable pre-commit CI

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-content-trust#36]
### Details

> @awwad let's merge this so pre-commit can be installed locally and run as part of git commit hooks, we will postpone enabling pre-commit CI

_Originally posted by @kenodegard in https://github.com/conda/conda-content-trust/issues/35#issuecomment-1205894867_

Discuss the security concerns we have for granting pre-commit CI access.

### Tasks

- [x] decide whether pre-commit CI is acceptable to use, the decision here should likely apply to **all** conda org projects

**Comment by kenodegard** [comment]
not stale

**Comment by jezdez** [comment]
We've long ago decided to trust pre-commit.ci for other projects, so I've just enabled it for this repo as well. We'll be able to review changes to the code during the release process, to make sure no unexpected code change has happened.
