### ISSUE TITLE
`conda-content-trust` is incompatible with `cryptography=41.0.0`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-content-trust#56]
### What happened?

The recently released [`cryptography=41.0.0`](https://cryptography.io/en/latest/changelog/#v41-0-0) introduces breaking changes that are incompatible with `conda-content-trust`.

To reproduce:

```
CONDA_CHANNELS=conda-forge conda create -n scratch conda-content-trust cryptography=41
conda run -n scratch python -c "from conda_content_trust.common import SignatureError"
```

This was discovered while running conda's conda-forge test suite: https://github.com/conda/conda/actions/runs/5137836382/jobs/9249611836

**Comment by jezdez** [comment]
This is related to implementing ed25519 in Rust: https://github.com/pyca/cryptography/pull/8697
