### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by dholth** [conda/conda-content-trust#72]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

conda-content-trust should have 100% test coverage

### Linked Issues & PRs

- [ ] #

**Comment by kenodegard** [comment]
Completed, see https://app.codecov.io/gh/conda/conda-content-trust/commit/51551f34b59dd541148c3333bf85e137d0e980d7
