### ISSUE TITLE
Cache public key

### ISSUE THREAD

**Issue by dholth** [conda/conda-content-trust#83]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Don't create new PublicKey() for each signature verification, when many are being verified against the same key. May save ~750ms.

### Why is this needed?

Discovered from benchmark https://github.com/conda/conda-content-trust/actions/runs/6163081698/job/16725868947#step:8:133

### What should happen?

conda-content-trust (or the calling code in conda) should create one PublicKey() per unique signing key.

**Comment by mohanavamsi20** [comment]
use one key for every unique signing key, it makes it faster and more efficient than creating new for each signature
