### ISSUE TITLE
Do we need `securesystemslib`?

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-content-trust#91]
### What happened?

`securesystemslib` was [only recently added to `conda-forge`](https://github.com/conda-forge/staged-recipes/pull/23723) and is not available on `defaults`. In other words, this feature has not been in use outside of development/testing.

Do we need to continue to offer this functionality?

**Comment by mohanavamsi20** [comment]
It can be usefull for future references or experiment.

**Comment by chenghlee** [comment]
It's "needed" for operations like [signing the trust roots](https://github.com/conda/conda-content-trust/blob/369132c/conda_content_trust/root_signing.py#L49).

However, I'd argue that the trust metadata signing and management should be re-factored into a separate package/utility, and `conda-content-trust` be re-scoped to only be the client-side trust verification component. And in that case, `securesystemslib` shouldn't be needed as a dependency, as any other, trustworthy package that supports Ed25519 verification would work.
